# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 40, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.add_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.add_filter_button.setGeometry(QtCore.QRect(100, 70, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_filter_button.setFont(font)
        self.add_filter_button.setObjectName("add_filter_button")
        self.filter_type_label = QtWidgets.QLabel(self.groupBox)
        self.filter_type_label.setGeometry(QtCore.QRect(10, 30, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filter_type_label.setFont(font)
        self.filter_type_label.setObjectName("filter_type_label")
        self.add_filter_combo = QtWidgets.QComboBox(self.groupBox)
        self.add_filter_combo.setGeometry(QtCore.QRect(100, 30, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_filter_combo.setFont(font)
        self.add_filter_combo.setObjectName("add_filter_combo")
        self.report_generation_button = QtWidgets.QPushButton(self.centralwidget)
        self.report_generation_button.setGeometry(QtCore.QRect(780, 450, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.report_generation_button.setFont(font)
        self.report_generation_button.setObjectName("report_generation_button")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(610, 40, 311, 391))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setGeometry(QtCore.QRect(20, 30, 256, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.delete_filter_button = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_filter_button.setGeometry(QtCore.QRect(20, 350, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_filter_button.setFont(font)
        self.delete_filter_button.setObjectName("delete_filter_button")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(360, 160, 231, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.criterio_label = QtWidgets.QLabel(self.groupBox_3)
        self.criterio_label.setGeometry(QtCore.QRect(20, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.criterio_label.setFont(font)
        self.criterio_label.setObjectName("criterio_label")
        self.criteria_combobox = QtWidgets.QComboBox(self.groupBox_3)
        self.criteria_combobox.setGeometry(QtCore.QRect(100, 30, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.criteria_combobox.setFont(font)
        self.criteria_combobox.setObjectName("criteria_combobox")
        self.criteria_combobox.addItem("")
        self.criteria_combobox.addItem("")
        self.criteria_combobox.addItem("")
        self.criteria_combobox.addItem("")
        self.description_label = QtWidgets.QLabel(self.groupBox_3)
        self.description_label.setGeometry(QtCore.QRect(20, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.description_label.setFont(font)
        self.description_label.setObjectName("description_label")
        self.description_text = QtWidgets.QLabel(self.groupBox_3)
        self.description_text.setGeometry(QtCore.QRect(20, 100, 191, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.description_text.setFont(font)
        self.description_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description_text.setWordWrap(True)
        self.description_text.setObjectName("description_text")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 43, 321, 181))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.initial_csv_path_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.initial_csv_path_input.setGeometry(QtCore.QRect(150, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.initial_csv_path_input.setFont(font)
        self.initial_csv_path_input.setFrame(False)
        self.initial_csv_path_input.setReadOnly(True)
        self.initial_csv_path_input.setObjectName("initial_csv_path_input")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sensibility_table_path_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.sensibility_table_path_input.setGeometry(QtCore.QRect(150, 60, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sensibility_table_path_input.setFont(font)
        self.sensibility_table_path_input.setFrame(False)
        self.sensibility_table_path_input.setReadOnly(True)
        self.sensibility_table_path_input.setObjectName("sensibility_table_path_input")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dtr_fenotype_path_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.dtr_fenotype_path_input.setGeometry(QtCore.QRect(150, 90, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dtr_fenotype_path_input.setFont(font)
        self.dtr_fenotype_path_input.setFrame(False)
        self.dtr_fenotype_path_input.setReadOnly(True)
        self.dtr_fenotype_path_input.setObjectName("dtr_fenotype_path_input")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 122, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.final_csv_path_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.final_csv_path_input.setGeometry(QtCore.QRect(150, 122, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.final_csv_path_input.setFont(font)
        self.final_csv_path_input.setFrame(False)
        self.final_csv_path_input.setReadOnly(True)
        self.final_csv_path_input.setObjectName("final_csv_path_input")
        self.csv_resistance_path_button = QtWidgets.QToolButton(self.groupBox_4)
        self.csv_resistance_path_button.setGeometry(QtCore.QRect(290, 29, 21, 21))
        self.csv_resistance_path_button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.csv_resistance_path_button.setAutoRaise(True)
        self.csv_resistance_path_button.setObjectName("csv_resistance_path_button")
        self.sensibility_table_path_button = QtWidgets.QToolButton(self.groupBox_4)
        self.sensibility_table_path_button.setGeometry(QtCore.QRect(290, 60, 21, 21))
        self.sensibility_table_path_button.setAutoRaise(True)
        self.sensibility_table_path_button.setObjectName("sensibility_table_path_button")
        self.dtr_fenotype_button = QtWidgets.QToolButton(self.groupBox_4)
        self.dtr_fenotype_button.setGeometry(QtCore.QRect(290, 90, 21, 21))
        self.dtr_fenotype_button.setAutoRaise(True)
        self.dtr_fenotype_button.setObjectName("dtr_fenotype_button")
        self.final_csv_path_button = QtWidgets.QToolButton(self.groupBox_4)
        self.final_csv_path_button.setGeometry(QtCore.QRect(290, 122, 21, 21))
        self.final_csv_path_button.setAutoRaise(True)
        self.final_csv_path_button.setObjectName("final_csv_path_button")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(29, 229, 321, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.dtr_description_text = QtWidgets.QLabel(self.groupBox_5)
        self.dtr_description_text.setGeometry(QtCore.QRect(10, 90, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dtr_description_text.setFont(font)
        self.dtr_description_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dtr_description_text.setWordWrap(True)
        self.dtr_description_text.setObjectName("dtr_description_text")
        self.dtr_fenotype_checkbox = QtWidgets.QCheckBox(self.groupBox_5)
        self.dtr_fenotype_checkbox.setGeometry(QtCore.QRect(10, 30, 201, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dtr_fenotype_checkbox.setFont(font)
        self.dtr_fenotype_checkbox.setObjectName("dtr_fenotype_checkbox")
        self.dtr_description_label = QtWidgets.QLabel(self.groupBox_5)
        self.dtr_description_label.setGeometry(QtCore.QRect(9, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dtr_description_label.setFont(font)
        self.dtr_description_label.setObjectName("dtr_description_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Crear filtro"))
        self.add_filter_button.setText(_translate("MainWindow", "Añadir"))
        self.filter_type_label.setText(_translate("MainWindow", "Tipo de filtro"))
        self.report_generation_button.setText(_translate("MainWindow", "Generar informe"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filtros"))
        self.delete_filter_button.setText(_translate("MainWindow", "Eliminar filtro"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Seleccionar criterio"))
        self.criterio_label.setText(_translate("MainWindow", "Criterio"))
        self.criteria_combobox.setItemText(0, _translate("MainWindow", "Ninguno"))
        self.criteria_combobox.setItemText(1, _translate("MainWindow", "Primero"))
        self.criteria_combobox.setItemText(2, _translate("MainWindow", "Segundo"))
        self.criteria_combobox.setItemText(3, _translate("MainWindow", "Tercero"))
        self.description_label.setText(_translate("MainWindow", "Descripción"))
        self.description_text.setText(_translate("MainWindow", "Description "))
        self.groupBox_4.setTitle(_translate("MainWindow", "Rutas"))
        self.label.setText(_translate("MainWindow", "CSV de resistencia"))
        self.label_2.setText(_translate("MainWindow", "Tabla de sensibilidad"))
        self.label_3.setText(_translate("MainWindow", "Fenotipo DTR"))
        self.label_4.setText(_translate("MainWindow", "CSV de resistencia final"))
        self.csv_resistance_path_button.setText(_translate("MainWindow", "..."))
        self.sensibility_table_path_button.setText(_translate("MainWindow", "..."))
        self.dtr_fenotype_button.setText(_translate("MainWindow", "..."))
        self.final_csv_path_button.setText(_translate("MainWindow", "..."))
        self.groupBox_5.setTitle(_translate("MainWindow", "Fenotipo DTR CR ECR FQR"))
        self.dtr_description_text.setText(_translate("MainWindow", "Tabla de frecuencias sobre la pertenencia a cuatro fenotipos jerarquizados: DTR > CR > ECR > FQR. Si pasan más de 30 días entre microorganismos se consideran diferentes, si no, se aplica la jerarquía anterior."))
        self.dtr_fenotype_checkbox.setText(_translate("MainWindow", "Incluir análisis del fenotipo"))
        self.dtr_description_label.setText(_translate("MainWindow", "Descripción"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
